// describe('visits the local host', () => {
//   it('passes', () => {
//     cy.visit('http://localhost:8080/')
//   })
// })


it("Creates a line graph", function () {
  cy.visit("http://localhost:8080/")
  cy.contains("Line").click()
  cy.get("#chart-title-input").type("Test Line Graph")
  cy.get("#x-label-input").type("X Label")
  cy.get("#y-label-input").type("Y Label")
  cy.get(".x-value-input").type("25")
  cy.get(".y-value-input").type("50")
  cy.get("#generate-chart-btn").click()
  cy.get("#chart-img").should("exist")
})

it("Creates a bar graph", function () {
  cy.visit("http://localhost:8080/")
  cy.contains("Bar").click()
  cy.get("#chart-title-input").type("Test Bar Graph")
  cy.get("#x-label-input").type("X Label")
  cy.get("#y-label-input").type("Y Label")
  cy.get(".x-value-input").type("25")
  cy.get(".y-value-input").type("50")
  cy.get("#generate-chart-btn").click()
  cy.get("#chart-img").should("exist")
})

it("Creates a Scatter Plot", function () {
  cy.visit("http://localhost:8080/")
  cy.contains("Scatter").click()
  cy.get("#chart-title-input").type("Test Scatter Plot")
  cy.get("#x-label-input").type("X Label")
  cy.get("#y-label-input").type("Y Label")
  cy.get(".x-value-input").type("25")
  cy.get(".y-value-input").type("50")
  cy.get("#generate-chart-btn").click()
  cy.get("#chart-img").should("exist")
})

it("Checks that data is maintained", function () {
  cy.visit("http://localhost:8080/")
  cy.contains("Line").click()
  cy.get("#chart-title-input").type("Test Graph")
  cy.get("#x-label-input").type("X Data")
  cy.get("#y-label-input").type("Y Data")
  cy.get("#add-values-btn").click()
  cy.get("#add-values-btn").click()
  cy.get(":nth-child(4) > .x-value-input").type("25")
  cy.get(":nth-child(6) > .x-value-input").type("5")
  cy.get(":nth-child(8) > .x-value-input").type("10")
  cy.get(":nth-child(5) > .y-value-input").type("50")
  cy.get(":nth-child(7) > .y-value-input").type("5")
  cy.get(":nth-child(9) > .y-value-input").type("10")
  cy.contains("Scatter").click()
  cy.get(":nth-child(4) > .x-value-input").should('have.value', '25')
  cy.get(":nth-child(6) > .x-value-input").should('have.value', '5')
  cy.get(":nth-child(8) > .x-value-input").should('have.value', '10')
  cy.get(":nth-child(5) > .y-value-input").should('have.value', '50')
  cy.get(":nth-child(7) > .y-value-input").should('have.value', '5')
  cy.get(":nth-child(9) > .y-value-input").should('have.value', '10')
})

it("Asserts that saving a graph works.", function () {
  cy.visit("http://localhost:8080/")
  cy.contains("Bar").click()
  cy.get("#chart-title-input").type("Test Bar Graph")
  cy.get("#x-label-input").type("X Label")
  cy.get("#y-label-input").type("Y Label")
  cy.get(".x-value-input").type("25")
  cy.get(".y-value-input").type("50")
  cy.get("#generate-chart-btn").click()
  cy.get("#save-chart-btn").click()
  cy.contains("Gallery").click()
  cy.get(".chart-card").should("exist")
})

it("Checks that a saved chart can be reopened", function () {
  cy.visit("http://localhost:8080/")
  cy.contains("Line").click()
  cy.get("#chart-title-input").type("Test Graph")
  cy.get("#x-label-input").type("X Data")
  cy.get("#y-label-input").type("Y Data")
  cy.get("#add-values-btn").click()
  cy.get("#add-values-btn").click()
  cy.get(":nth-child(4) > .x-value-input").type("25")
  cy.get(":nth-child(6) > .x-value-input").type("5")
  cy.get(":nth-child(8) > .x-value-input").type("10")
  cy.get(":nth-child(5) > .y-value-input").type("50")
  cy.get(":nth-child(7) > .y-value-input").type("5")
  cy.get(":nth-child(9) > .y-value-input").type("10")
  cy.get("#generate-chart-btn").click()
  cy.get("#save-chart-btn").click()
  cy.contains("Gallery").click()
  cy.get(".chart-card").click()
  cy.get("#chart-title-input").should("have.value", "Test Graph")
  cy.get("#x-label-input").should("have.value", "X Data")
  cy.get("#y-label-input").should("have.value", "Y Data")
  cy.get(":nth-child(4) > .x-value-input").should('have.value', '25')
  cy.get(":nth-child(6) > .x-value-input").should('have.value', '5')
  cy.get(":nth-child(8) > .x-value-input").should('have.value', '10')
  cy.get(":nth-child(5) > .y-value-input").should('have.value', '50')
  cy.get(":nth-child(7) > .y-value-input").should('have.value', '5')
  cy.get(":nth-child(9) > .y-value-input").should('have.value', '10')
  cy.get("#chart-img").should("exist")
})

